package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strings"
	"time"

	"github.com/gambchamp/crm/pkg/errors"
	"github.com/gambchamp/crm/pkg/models"
)

type PDFHandler struct {
	store  *Store
	logger *slog.Logger
}

func NewPDFHandler(store *Store, logger *slog.Logger) *PDFHandler {
	return &PDFHandler{store: store, logger: logger}
}

func (ph *PDFHandler) GenerateVerificationCard(w http.ResponseWriter, r *http.Request) {
	tenantID := r.Header.Get("X-Tenant-ID")
	leadID := r.PathValue("lead_id")
	if tenantID == "" || leadID == "" {
		errors.NewBadRequest("tenant_id and lead_id required").WriteJSON(w)
		return
	}

	result, err := ph.store.GetFraudCheckResult(r.Context(), tenantID, leadID)
	if err != nil {
		ph.logger.Error("failed to get fraud check result", "error", err, "lead_id", leadID)
		errors.ErrInternal.WriteJSON(w)
		return
	}
	if result == nil {
		errors.ErrNotFound.WriteJSON(w)
		return
	}

	var checks []models.FraudCheck
	if len(result.Checks) > 0 {
		json.Unmarshal(result.Checks, &checks)
	}

	var ipData map[string]interface{}
	if len(result.IPData) > 0 {
		json.Unmarshal(result.IPData, &ipData)
	}

	var phoneData map[string]interface{}
	if len(result.PhoneData) > 0 {
		json.Unmarshal(result.PhoneData, &phoneData)
	}

	pdf := generateVerificationPDF(result, checks, ipData, phoneData)

	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="fraud-verification-%s.pdf"`, leadID))
	w.Header().Set("Content-Length", fmt.Sprintf("%d", len(pdf)))
	w.WriteHeader(http.StatusOK)
	w.Write(pdf)
}

func generateVerificationPDF(result *models.FraudCheckResult, checks []models.FraudCheck, ipData, phoneData map[string]interface{}) []byte {
	var buf bytes.Buffer

	buf.WriteString("%PDF-1.4\n")

	verdictColor := "0 0.6 0"
	if result.Verdict == "rejected" {
		verdictColor = "0.8 0 0"
	} else if result.Verdict == "review" {
		verdictColor = "0.9 0.6 0"
	}

	title := "GambChamp CRM - Fraud Verification Card"
	leadLine := fmt.Sprintf("Lead ID: %s", result.LeadID)
	scoreLine := fmt.Sprintf("Overall Score: %d / 100", result.OverallScore)
	verdictLine := fmt.Sprintf("Verdict: %s", strings.ToUpper(result.Verdict))
	checkedLine := fmt.Sprintf("Checked At: %s", result.CheckedAt.Format(time.RFC3339))

	var checkLines []string
	checkLines = append(checkLines, "")
	checkLines = append(checkLines, "=== Check Breakdown ===")
	categoryScores := make(map[string]struct{ score, max int })
	for _, c := range checks {
		cat := categoryScores[c.Category]
		cat.score += c.Score
		cat.max += c.MaxScore
		categoryScores[c.Category] = cat
	}
	for cat, s := range categoryScores {
		checkLines = append(checkLines, fmt.Sprintf("  %s: %d / %d", strings.Title(cat), s.score, s.max))
	}

	checkLines = append(checkLines, "")
	checkLines = append(checkLines, "=== Detailed Checks ===")
	for _, c := range checks {
		line := fmt.Sprintf("  [%s] %s: %d/%d (%s) - %s",
			c.Category, c.CheckName, c.Score, c.MaxScore, c.Result, c.Explanation)
		checkLines = append(checkLines, line)
	}

	if ipData != nil {
		checkLines = append(checkLines, "")
		checkLines = append(checkLines, "=== IP Analysis ===")
		for k, v := range ipData {
			checkLines = append(checkLines, fmt.Sprintf("  %s: %v", k, v))
		}
	}

	if phoneData != nil {
		checkLines = append(checkLines, "")
		checkLines = append(checkLines, "=== Phone Analysis ===")
		for k, v := range phoneData {
			checkLines = append(checkLines, fmt.Sprintf("  %s: %v", k, v))
		}
	}

	checkLines = append(checkLines, "")
	checkLines = append(checkLines, fmt.Sprintf("Generated: %s", time.Now().UTC().Format(time.RFC3339)))
	checkLines = append(checkLines, "This document is auto-generated by GambChamp CRM Fraud Engine.")

	allText := []string{title, "", leadLine, scoreLine, verdictLine, checkedLine}
	allText = append(allText, checkLines...)

	textStream := buildPDFTextStream(allText, verdictColor)

	objects := []string{
		"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
		"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
		fmt.Sprintf("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj\n"),
		fmt.Sprintf("4 0 obj\n<< /Length %d >>\nstream\n%s\nendstream\nendobj\n", len(textStream), textStream),
		"5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>\nendobj\n",
		"6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Courier-Bold >>\nendobj\n",
	}

	offsets := make([]int, len(objects))
	for i, obj := range objects {
		offsets[i] = buf.Len()
		buf.WriteString(obj)
	}

	xrefOffset := buf.Len()
	buf.WriteString(fmt.Sprintf("xref\n0 %d\n", len(objects)+1))
	buf.WriteString("0000000000 65535 f \n")
	for _, off := range offsets {
		buf.WriteString(fmt.Sprintf("%010d 00000 n \n", off))
	}

	buf.WriteString("trailer\n")
	buf.WriteString(fmt.Sprintf("<< /Size %d /Root 1 0 R >>\n", len(objects)+1))
	buf.WriteString("startxref\n")
	buf.WriteString(fmt.Sprintf("%d\n", xrefOffset))
	buf.WriteString("%%EOF\n")

	return buf.Bytes()
}

func buildPDFTextStream(lines []string, verdictColor string) string {
	var stream bytes.Buffer
	stream.WriteString("BT\n")
	y := 750.0

	for i, line := range lines {
		if y < 40 {
			break
		}

		if i == 0 {
			stream.WriteString("/F2 14 Tf\n")
			stream.WriteString("0 0.3 0.6 rg\n")
		} else if strings.HasPrefix(line, "Verdict:") {
			stream.WriteString("/F2 12 Tf\n")
			stream.WriteString(fmt.Sprintf("%s rg\n", verdictColor))
		} else if strings.HasPrefix(line, "===") {
			stream.WriteString("/F2 10 Tf\n")
			stream.WriteString("0.2 0.2 0.2 rg\n")
		} else {
			stream.WriteString("/F1 9 Tf\n")
			stream.WriteString("0.3 0.3 0.3 rg\n")
		}

		escaped := strings.ReplaceAll(line, "\\", "\\\\")
		escaped = strings.ReplaceAll(escaped, "(", "\\(")
		escaped = strings.ReplaceAll(escaped, ")", "\\)")

		stream.WriteString(fmt.Sprintf("1 0 0 1 40 %.0f Tm\n", y))
		stream.WriteString(fmt.Sprintf("(%s) Tj\n", escaped))

		if i == 0 {
			y -= 24
		} else {
			y -= 14
		}
	}

	stream.WriteString("ET\n")
	return stream.String()
}
