// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: affiliates.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countAffiliates = `-- name: CountAffiliates :one
SELECT count(*) FROM affiliates WHERE company_id = $1
`

func (q *Queries) CountAffiliates(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAffiliates, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAffiliate = `-- name: CreateAffiliate :one
INSERT INTO affiliates (company_id, name, api_key, email, status, settings)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, name, api_key, email, status, settings, created_at
`

type CreateAffiliateParams struct {
	CompanyID uuid.UUID       `json:"company_id"`
	Name      string          `json:"name"`
	ApiKey    string          `json:"api_key"`
	Email     *string         `json:"email"`
	Status    string          `json:"status"`
	Settings  json.RawMessage `json:"settings"`
}

func (q *Queries) CreateAffiliate(ctx context.Context, arg CreateAffiliateParams) (Affiliate, error) {
	row := q.db.QueryRow(ctx, createAffiliate,
		arg.CompanyID,
		arg.Name,
		arg.ApiKey,
		arg.Email,
		arg.Status,
		arg.Settings,
	)
	var i Affiliate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ApiKey,
		&i.Email,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getAffiliate = `-- name: GetAffiliate :one
SELECT id, company_id, name, api_key, email, status, settings, created_at FROM affiliates WHERE id = $1 AND company_id = $2
`

type GetAffiliateParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetAffiliate(ctx context.Context, arg GetAffiliateParams) (Affiliate, error) {
	row := q.db.QueryRow(ctx, getAffiliate, arg.ID, arg.CompanyID)
	var i Affiliate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ApiKey,
		&i.Email,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getAffiliateByAPIKey = `-- name: GetAffiliateByAPIKey :one
SELECT id, company_id, name, api_key, email, status, settings, created_at FROM affiliates WHERE api_key = $1
`

func (q *Queries) GetAffiliateByAPIKey(ctx context.Context, apiKey string) (Affiliate, error) {
	row := q.db.QueryRow(ctx, getAffiliateByAPIKey, apiKey)
	var i Affiliate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ApiKey,
		&i.Email,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const listAffiliates = `-- name: ListAffiliates :many
SELECT id, company_id, name, api_key, email, status, settings, created_at FROM affiliates
WHERE company_id = $1
  AND ($4::varchar IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAffiliatesParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
	Status    *string   `json:"status"`
}

func (q *Queries) ListAffiliates(ctx context.Context, arg ListAffiliatesParams) ([]Affiliate, error) {
	rows, err := q.db.Query(ctx, listAffiliates,
		arg.CompanyID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Affiliate{}
	for rows.Next() {
		var i Affiliate
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.ApiKey,
			&i.Email,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAffiliate = `-- name: UpdateAffiliate :one
UPDATE affiliates
SET name = COALESCE($3, name),
    email = COALESCE($4, email),
    status = COALESCE($5, status),
    settings = COALESCE($6, settings)
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, api_key, email, status, settings, created_at
`

type UpdateAffiliateParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Name      *string   `json:"name"`
	Email     *string   `json:"email"`
	Status    *string   `json:"status"`
	Settings  []byte    `json:"settings"`
}

func (q *Queries) UpdateAffiliate(ctx context.Context, arg UpdateAffiliateParams) (Affiliate, error) {
	row := q.db.QueryRow(ctx, updateAffiliate,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Email,
		arg.Status,
		arg.Settings,
	)
	var i Affiliate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ApiKey,
		&i.Email,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const updateAffiliateAPIKey = `-- name: UpdateAffiliateAPIKey :one
UPDATE affiliates SET api_key = $3 WHERE id = $1 AND company_id = $2 RETURNING id, company_id, name, api_key, email, status, settings, created_at
`

type UpdateAffiliateAPIKeyParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	ApiKey    string    `json:"api_key"`
}

func (q *Queries) UpdateAffiliateAPIKey(ctx context.Context, arg UpdateAffiliateAPIKeyParams) (Affiliate, error) {
	row := q.db.QueryRow(ctx, updateAffiliateAPIKey, arg.ID, arg.CompanyID, arg.ApiKey)
	var i Affiliate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ApiKey,
		&i.Email,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}
