// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, slug, plan, status, settings)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, plan, status, settings, created_at, updated_at
`

type CreateCompanyParams struct {
	Name     string          `json:"name"`
	Slug     string          `json:"slug"`
	Plan     string          `json:"plan"`
	Status   string          `json:"status"`
	Settings json.RawMessage `json:"settings"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.Status,
		arg.Settings,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, slug, plan, status, settings, created_at, updated_at FROM companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, slug, plan, status, settings, created_at, updated_at FROM companies ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListCompaniesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    plan = COALESCE($4, plan),
    status = COALESCE($5, status),
    settings = COALESCE($6, settings),
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, plan, status, settings, created_at, updated_at
`

type UpdateCompanyParams struct {
	ID       uuid.UUID `json:"id"`
	Name     *string   `json:"name"`
	Slug     *string   `json:"slug"`
	Plan     *string   `json:"plan"`
	Status   *string   `json:"status"`
	Settings []byte    `json:"settings"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.Status,
		arg.Settings,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
