// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkDuplicate = `-- name: CheckDuplicate :one
SELECT 1 FROM leads
WHERE company_id = $1 AND (email = $2 OR phone = $3)
  AND created_at > now() - interval '30 days'
LIMIT 1
`

type CheckDuplicateParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
}

func (q *Queries) CheckDuplicate(ctx context.Context, arg CheckDuplicateParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkDuplicate, arg.CompanyID, arg.Email, arg.Phone)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countLeads = `-- name: CountLeads :one
SELECT count(*) FROM leads
WHERE company_id = $1
  AND ($2::varchar IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR affiliate_id = $3)
  AND ($4::char(2) IS NULL OR country = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
  AND ($7::varchar IS NULL OR email ILIKE '%' || $7 || '%' OR phone ILIKE '%' || $7 || '%')
`

type CountLeadsParams struct {
	CompanyID   uuid.UUID          `json:"company_id"`
	Status      *string            `json:"status"`
	AffiliateID pgtype.UUID        `json:"affiliate_id"`
	Country     *string            `json:"country"`
	DateFrom    pgtype.Timestamptz `json:"date_from"`
	DateTo      pgtype.Timestamptz `json:"date_to"`
	Search      *string            `json:"search"`
}

func (q *Queries) CountLeads(ctx context.Context, arg CountLeadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLeads,
		arg.CompanyID,
		arg.Status,
		arg.AffiliateID,
		arg.Country,
		arg.DateFrom,
		arg.DateTo,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (
  company_id, affiliate_id, first_name, last_name, email, phone, phone_raw,
  country, ip, language, funnel_id, click_id,
  sub_id_1, sub_id_2, sub_id_3, sub_id_4, sub_id_5,
  custom_fields, status, idempotency_key, source_api_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
RETURNING id, company_id, affiliate_id, first_name, last_name, email, phone, phone_raw, country, ip, language, funnel_id, click_id, sub_id_1, sub_id_2, sub_id_3, sub_id_4, sub_id_5, custom_fields, status, fraud_score, fraud_details, idempotency_key, source_api_key, created_at, updated_at
`

type CreateLeadParams struct {
	CompanyID      uuid.UUID `json:"company_id"`
	AffiliateID    uuid.UUID `json:"affiliate_id"`
	FirstName      string    `json:"first_name"`
	LastName       *string   `json:"last_name"`
	Email          string    `json:"email"`
	Phone          string    `json:"phone"`
	PhoneRaw       *string   `json:"phone_raw"`
	Country        string    `json:"country"`
	Ip             string    `json:"ip"`
	Language       *string   `json:"language"`
	FunnelID       *string   `json:"funnel_id"`
	ClickID        *string   `json:"click_id"`
	SubID1         *string   `json:"sub_id_1"`
	SubID2         *string   `json:"sub_id_2"`
	SubID3         *string   `json:"sub_id_3"`
	SubID4         *string   `json:"sub_id_4"`
	SubID5         *string   `json:"sub_id_5"`
	CustomFields   []byte    `json:"custom_fields"`
	Status         string    `json:"status"`
	IdempotencyKey *string   `json:"idempotency_key"`
	SourceApiKey   *string   `json:"source_api_key"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.CompanyID,
		arg.AffiliateID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.PhoneRaw,
		arg.Country,
		arg.Ip,
		arg.Language,
		arg.FunnelID,
		arg.ClickID,
		arg.SubID1,
		arg.SubID2,
		arg.SubID3,
		arg.SubID4,
		arg.SubID5,
		arg.CustomFields,
		arg.Status,
		arg.IdempotencyKey,
		arg.SourceApiKey,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AffiliateID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.PhoneRaw,
		&i.Country,
		&i.Ip,
		&i.Language,
		&i.FunnelID,
		&i.ClickID,
		&i.SubID1,
		&i.SubID2,
		&i.SubID3,
		&i.SubID4,
		&i.SubID5,
		&i.CustomFields,
		&i.Status,
		&i.FraudScore,
		&i.FraudDetails,
		&i.IdempotencyKey,
		&i.SourceApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLead = `-- name: GetLead :one
SELECT id, company_id, affiliate_id, first_name, last_name, email, phone, phone_raw, country, ip, language, funnel_id, click_id, sub_id_1, sub_id_2, sub_id_3, sub_id_4, sub_id_5, custom_fields, status, fraud_score, fraud_details, idempotency_key, source_api_key, created_at, updated_at FROM leads WHERE id = $1 AND company_id = $2
`

type GetLeadParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetLead(ctx context.Context, arg GetLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, getLead, arg.ID, arg.CompanyID)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AffiliateID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.PhoneRaw,
		&i.Country,
		&i.Ip,
		&i.Language,
		&i.FunnelID,
		&i.ClickID,
		&i.SubID1,
		&i.SubID2,
		&i.SubID3,
		&i.SubID4,
		&i.SubID5,
		&i.CustomFields,
		&i.Status,
		&i.FraudScore,
		&i.FraudDetails,
		&i.IdempotencyKey,
		&i.SourceApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeadUnscoped = `-- name: GetLeadUnscoped :one
SELECT id, company_id, affiliate_id, first_name, last_name, email, phone, phone_raw, country, ip, language, funnel_id, click_id, sub_id_1, sub_id_2, sub_id_3, sub_id_4, sub_id_5, custom_fields, status, fraud_score, fraud_details, idempotency_key, source_api_key, created_at, updated_at FROM leads WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLeadUnscoped(ctx context.Context, id uuid.UUID) (Lead, error) {
	row := q.db.QueryRow(ctx, getLeadUnscoped, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AffiliateID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.PhoneRaw,
		&i.Country,
		&i.Ip,
		&i.Language,
		&i.FunnelID,
		&i.ClickID,
		&i.SubID1,
		&i.SubID2,
		&i.SubID3,
		&i.SubID4,
		&i.SubID5,
		&i.CustomFields,
		&i.Status,
		&i.FraudScore,
		&i.FraudDetails,
		&i.IdempotencyKey,
		&i.SourceApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeads = `-- name: ListLeads :many
SELECT id, company_id, affiliate_id, first_name, last_name, email, phone, phone_raw, country, ip, language, funnel_id, click_id, sub_id_1, sub_id_2, sub_id_3, sub_id_4, sub_id_5, custom_fields, status, fraud_score, fraud_details, idempotency_key, source_api_key, created_at, updated_at FROM leads
WHERE company_id = $1
  AND ($4::varchar IS NULL OR status = $4)
  AND ($5::uuid IS NULL OR affiliate_id = $5)
  AND ($6::char(2) IS NULL OR country = $6)
  AND ($7::timestamptz IS NULL OR created_at >= $7)
  AND ($8::timestamptz IS NULL OR created_at <= $8)
  AND ($9::varchar IS NULL OR email ILIKE '%' || $9 || '%' OR phone ILIKE '%' || $9 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLeadsParams struct {
	CompanyID   uuid.UUID          `json:"company_id"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
	Status      *string            `json:"status"`
	AffiliateID pgtype.UUID        `json:"affiliate_id"`
	Country     *string            `json:"country"`
	DateFrom    pgtype.Timestamptz `json:"date_from"`
	DateTo      pgtype.Timestamptz `json:"date_to"`
	Search      *string            `json:"search"`
}

func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeads,
		arg.CompanyID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.AffiliateID,
		arg.Country,
		arg.DateFrom,
		arg.DateTo,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.AffiliateID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.PhoneRaw,
			&i.Country,
			&i.Ip,
			&i.Language,
			&i.FunnelID,
			&i.ClickID,
			&i.SubID1,
			&i.SubID2,
			&i.SubID3,
			&i.SubID4,
			&i.SubID5,
			&i.CustomFields,
			&i.Status,
			&i.FraudScore,
			&i.FraudDetails,
			&i.IdempotencyKey,
			&i.SourceApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeadFraud = `-- name: UpdateLeadFraud :exec
UPDATE leads
SET fraud_score = $3, fraud_details = $4, status = $5, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateLeadFraudParams struct {
	ID           uuid.UUID `json:"id"`
	CompanyID    uuid.UUID `json:"company_id"`
	FraudScore   *int16    `json:"fraud_score"`
	FraudDetails []byte    `json:"fraud_details"`
	Status       string    `json:"status"`
}

func (q *Queries) UpdateLeadFraud(ctx context.Context, arg UpdateLeadFraudParams) error {
	_, err := q.db.Exec(ctx, updateLeadFraud,
		arg.ID,
		arg.CompanyID,
		arg.FraudScore,
		arg.FraudDetails,
		arg.Status,
	)
	return err
}

const updateLeadStatus = `-- name: UpdateLeadStatus :exec
UPDATE leads SET status = $3, updated_at = now() WHERE id = $1 AND company_id = $2
`

type UpdateLeadStatusParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) error {
	_, err := q.db.Exec(ctx, updateLeadStatus, arg.ID, arg.CompanyID, arg.Status)
	return err
}
