// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Affiliate struct {
	ID        uuid.UUID       `json:"id"`
	CompanyID uuid.UUID       `json:"company_id"`
	Name      string          `json:"name"`
	ApiKey    string          `json:"api_key"`
	Email     *string         `json:"email"`
	Status    string          `json:"status"`
	Settings  json.RawMessage `json:"settings"`
	CreatedAt time.Time       `json:"created_at"`
}

type ApiRequestLog struct {
	ID         int64       `json:"id"`
	RequestID  uuid.UUID   `json:"request_id"`
	CompanyID  pgtype.UUID `json:"company_id"`
	ApiKeyID   pgtype.UUID `json:"api_key_id"`
	Endpoint   *string     `json:"endpoint"`
	Method     *string     `json:"method"`
	StatusCode *int16      `json:"status_code"`
	LatencyMs  *int32      `json:"latency_ms"`
	Ip         string      `json:"ip"`
	CreatedAt  time.Time   `json:"created_at"`
}

type ApiRequestLog202603 struct {
	ID         int64       `json:"id"`
	RequestID  uuid.UUID   `json:"request_id"`
	CompanyID  pgtype.UUID `json:"company_id"`
	ApiKeyID   pgtype.UUID `json:"api_key_id"`
	Endpoint   *string     `json:"endpoint"`
	Method     *string     `json:"method"`
	StatusCode *int16      `json:"status_code"`
	LatencyMs  *int32      `json:"latency_ms"`
	Ip         string      `json:"ip"`
	CreatedAt  time.Time   `json:"created_at"`
}

type ApiRequestLog202604 struct {
	ID         int64       `json:"id"`
	RequestID  uuid.UUID   `json:"request_id"`
	CompanyID  pgtype.UUID `json:"company_id"`
	ApiKeyID   pgtype.UUID `json:"api_key_id"`
	Endpoint   *string     `json:"endpoint"`
	Method     *string     `json:"method"`
	StatusCode *int16      `json:"status_code"`
	LatencyMs  *int32      `json:"latency_ms"`
	Ip         string      `json:"ip"`
	CreatedAt  time.Time   `json:"created_at"`
}

type ApiRequestLog202605 struct {
	ID         int64       `json:"id"`
	RequestID  uuid.UUID   `json:"request_id"`
	CompanyID  pgtype.UUID `json:"company_id"`
	ApiKeyID   pgtype.UUID `json:"api_key_id"`
	Endpoint   *string     `json:"endpoint"`
	Method     *string     `json:"method"`
	StatusCode *int16      `json:"status_code"`
	LatencyMs  *int32      `json:"latency_ms"`
	Ip         string      `json:"ip"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Company struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Plan      string          `json:"plan"`
	Status    string          `json:"status"`
	Settings  json.RawMessage `json:"settings"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Lead struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	AffiliateID    uuid.UUID `json:"affiliate_id"`
	FirstName      string    `json:"first_name"`
	LastName       *string   `json:"last_name"`
	Email          string    `json:"email"`
	Phone          string    `json:"phone"`
	PhoneRaw       *string   `json:"phone_raw"`
	Country        string    `json:"country"`
	Ip             string    `json:"ip"`
	Language       *string   `json:"language"`
	FunnelID       *string   `json:"funnel_id"`
	ClickID        *string   `json:"click_id"`
	SubID1         *string   `json:"sub_id_1"`
	SubID2         *string   `json:"sub_id_2"`
	SubID3         *string   `json:"sub_id_3"`
	SubID4         *string   `json:"sub_id_4"`
	SubID5         *string   `json:"sub_id_5"`
	CustomFields   []byte    `json:"custom_fields"`
	Status         string    `json:"status"`
	FraudScore     *int16    `json:"fraud_score"`
	FraudDetails   []byte    `json:"fraud_details"`
	IdempotencyKey *string   `json:"idempotency_key"`
	SourceApiKey   *string   `json:"source_api_key"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Leads202603 struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	AffiliateID    uuid.UUID `json:"affiliate_id"`
	FirstName      string    `json:"first_name"`
	LastName       *string   `json:"last_name"`
	Email          string    `json:"email"`
	Phone          string    `json:"phone"`
	PhoneRaw       *string   `json:"phone_raw"`
	Country        string    `json:"country"`
	Ip             string    `json:"ip"`
	Language       *string   `json:"language"`
	FunnelID       *string   `json:"funnel_id"`
	ClickID        *string   `json:"click_id"`
	SubID1         *string   `json:"sub_id_1"`
	SubID2         *string   `json:"sub_id_2"`
	SubID3         *string   `json:"sub_id_3"`
	SubID4         *string   `json:"sub_id_4"`
	SubID5         *string   `json:"sub_id_5"`
	CustomFields   []byte    `json:"custom_fields"`
	Status         string    `json:"status"`
	FraudScore     *int16    `json:"fraud_score"`
	FraudDetails   []byte    `json:"fraud_details"`
	IdempotencyKey *string   `json:"idempotency_key"`
	SourceApiKey   *string   `json:"source_api_key"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Leads202604 struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	AffiliateID    uuid.UUID `json:"affiliate_id"`
	FirstName      string    `json:"first_name"`
	LastName       *string   `json:"last_name"`
	Email          string    `json:"email"`
	Phone          string    `json:"phone"`
	PhoneRaw       *string   `json:"phone_raw"`
	Country        string    `json:"country"`
	Ip             string    `json:"ip"`
	Language       *string   `json:"language"`
	FunnelID       *string   `json:"funnel_id"`
	ClickID        *string   `json:"click_id"`
	SubID1         *string   `json:"sub_id_1"`
	SubID2         *string   `json:"sub_id_2"`
	SubID3         *string   `json:"sub_id_3"`
	SubID4         *string   `json:"sub_id_4"`
	SubID5         *string   `json:"sub_id_5"`
	CustomFields   []byte    `json:"custom_fields"`
	Status         string    `json:"status"`
	FraudScore     *int16    `json:"fraud_score"`
	FraudDetails   []byte    `json:"fraud_details"`
	IdempotencyKey *string   `json:"idempotency_key"`
	SourceApiKey   *string   `json:"source_api_key"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Leads202605 struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	AffiliateID    uuid.UUID `json:"affiliate_id"`
	FirstName      string    `json:"first_name"`
	LastName       *string   `json:"last_name"`
	Email          string    `json:"email"`
	Phone          string    `json:"phone"`
	PhoneRaw       *string   `json:"phone_raw"`
	Country        string    `json:"country"`
	Ip             string    `json:"ip"`
	Language       *string   `json:"language"`
	FunnelID       *string   `json:"funnel_id"`
	ClickID        *string   `json:"click_id"`
	SubID1         *string   `json:"sub_id_1"`
	SubID2         *string   `json:"sub_id_2"`
	SubID3         *string   `json:"sub_id_3"`
	SubID4         *string   `json:"sub_id_4"`
	SubID5         *string   `json:"sub_id_5"`
	CustomFields   []byte    `json:"custom_fields"`
	Status         string    `json:"status"`
	FraudScore     *int16    `json:"fraud_score"`
	FraudDetails   []byte    `json:"fraud_details"`
	IdempotencyKey *string   `json:"idempotency_key"`
	SourceApiKey   *string   `json:"source_api_key"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	Ip        string    `json:"ip"`
	UserAgent *string   `json:"user_agent"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Name         *string            `json:"name"`
	TotpSecret   *string            `json:"totp_secret"`
	TotpEnabled  bool               `json:"totp_enabled"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	Status       string             `json:"status"`
	CreatedAt    time.Time          `json:"created_at"`
}
