// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE company_id = $1
`

func (q *Queries) CountUsers(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (company_id, email, password_hash, role, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, email, password_hash, role, name, totp_secret, totp_enabled, last_login_at, status, created_at
`

type CreateUserParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Name         *string   `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.CompanyID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET status = 'inactive' WHERE id = $1 AND company_id = $2
`

type DeactivateUserParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) error {
	_, err := q.db.Exec(ctx, deactivateUser, arg.ID, arg.CompanyID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, company_id, email, password_hash, role, name, totp_secret, totp_enabled, last_login_at, status, created_at FROM users WHERE email = $1 AND company_id = $2
`

type GetUserByEmailParams struct {
	Email     string    `json:"email"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, company_id, email, password_hash, role, name, totp_secret, totp_enabled, last_login_at, status, created_at FROM users WHERE id = $1 AND company_id = $2
`

type GetUserByIDParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, company_id, email, password_hash, role, name, totp_secret, totp_enabled, last_login_at, status, created_at FROM users WHERE company_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Name,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.LastLoginAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserTOTP = `-- name: SetUserTOTP :exec
UPDATE users SET totp_secret = $3, totp_enabled = $4 WHERE id = $1 AND company_id = $2
`

type SetUserTOTPParams struct {
	ID          uuid.UUID `json:"id"`
	CompanyID   uuid.UUID `json:"company_id"`
	TotpSecret  *string   `json:"totp_secret"`
	TotpEnabled bool      `json:"totp_enabled"`
}

func (q *Queries) SetUserTOTP(ctx context.Context, arg SetUserTOTPParams) error {
	_, err := q.db.Exec(ctx, setUserTOTP,
		arg.ID,
		arg.CompanyID,
		arg.TotpSecret,
		arg.TotpEnabled,
	)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($3, name),
    role = COALESCE($4, role),
    status = COALESCE($5, status)
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, email, password_hash, role, name, totp_secret, totp_enabled, last_login_at, status, created_at
`

type UpdateUserParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Name      *string   `json:"name"`
	Role      *string   `json:"role"`
	Status    *string   `json:"status"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Role,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
