DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS notification_preferences CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS uad_queue CASCADE;
DROP TABLE IF EXISTS autologin_sessions CASCADE;
DROP TABLE IF EXISTS fraud_profiles CASCADE;
DROP TABLE IF EXISTS lead_events CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
-- Drop all lead partitions
DROP TABLE IF EXISTS leads_2026_01, leads_2026_02, leads_2026_03, leads_2026_04, leads_2026_05, leads_2026_06, leads_2026_07, leads_2026_08, leads_2026_09, leads_2026_10, leads_2026_11, leads_2026_12 CASCADE;
DROP TABLE IF EXISTS distribution_rules CASCADE;
DROP TABLE IF EXISTS brokers CASCADE;
DROP TABLE IF EXISTS broker_templates CASCADE;
DROP TABLE IF EXISTS affiliates CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP FUNCTION IF EXISTS update_updated_at();
