DROP INDEX IF EXISTS idx_leads_funnel;
DROP INDEX IF EXISTS idx_leads_tenant_phone_e164;

ALTER TABLE leads DROP COLUMN IF EXISTS aff_sub10;
ALTER TABLE leads DROP COLUMN IF EXISTS aff_sub9;
ALTER TABLE leads DROP COLUMN IF EXISTS aff_sub8;
ALTER TABLE leads DROP COLUMN IF EXISTS aff_sub7;
ALTER TABLE leads DROP COLUMN IF EXISTS aff_sub6;
ALTER TABLE leads DROP COLUMN IF EXISTS aff_sub5;
ALTER TABLE leads DROP COLUMN IF EXISTS aff_sub4;
ALTER TABLE leads DROP COLUMN IF EXISTS aff_sub3;
ALTER TABLE leads DROP COLUMN IF EXISTS aff_sub2;
ALTER TABLE leads DROP COLUMN IF EXISTS aff_sub1;
ALTER TABLE leads DROP COLUMN IF EXISTS funnel_name;
