import type { Prisma } from "@prisma/client";

export const binarycentStyle: Prisma.BrokerTemplateCreateInput = {
  slug: "binarycent-style-v1",
  name: "Binarycent-style (North America)",
  vendor: "Binarycent-style",
  vertical: "forex",
  protocol: "rest-json",
  status: "active",
  countries: ["US", "CA"],
  description: "Binarycent-style intake — bearer auth with slightly nested response.",
  defaultHttpMethod: "POST",
  defaultHeaders: { "content-type": "application/json" },
  defaultAuthType: "BEARER",
  authConfigSchema: {
    type: "object",
    required: ["token"],
    properties: { token: { type: "string", minLength: 20 } },
  },
  fieldMapping: {
    firstName: "first",
    lastName: "last",
    email: "email",
    phone: "tel",
    geo: "country",
    subId: "sub_id",
  },
  requiredFields: ["first", "last", "email", "tel", "country"],
  staticPayload: { source: "gambchamp", aff_vertical: "forex" },
  responseIdPath: "$.data.attributes.lead_id",
  postbackLeadIdPath: "$.lead_id",
  postbackStatusPath: "$.status",
  statusMapping: {
    submitted: "NEW",
    verified: "ACCEPTED",
    declined: "DECLINED",
    deposit: "FTD",
  },
  rateLimitPerMin: 60,
  samplePayload: {
    first: "Jane",
    last: "Doe",
    email: "jane@t.io",
    tel: "+14155551212",
    country: "US",
    sub_id: "bc-001",
  },
  sampleResponse: { data: { attributes: { lead_id: "bc-778899", status: "submitted" } } },
};
