import type { Prisma } from "@prisma/client";

export const iqoptionStyle: Prisma.BrokerTemplateCreateInput = {
  slug: "iqoption-style-v1",
  name: "IQOption-style (LatAm retail)",
  vendor: "IQOption-style",
  vertical: "forex",
  protocol: "rest-json",
  status: "active",
  countries: ["BR", "MX", "AR"],
  description: "Template modeled after IQOption-style affiliate intake used in LatAm.",
  defaultHttpMethod: "POST",
  defaultHeaders: { "content-type": "application/json" },
  defaultAuthType: "BEARER",
  authConfigSchema: {
    type: "object",
    required: ["token"],
    properties: { token: { type: "string", minLength: 24 } },
  },
  fieldMapping: {
    firstName: "name",
    lastName: "surname",
    email: "email",
    phone: "mobile",
    geo: "country_iso",
    subId: "aff_click_id",
  },
  requiredFields: ["name", "surname", "email", "mobile", "country_iso"],
  staticPayload: { channel: "gambchamp-crm" },
  responseIdPath: "$.data.id",
  postbackLeadIdPath: "$.id",
  postbackStatusPath: "$.event_type",
  statusMapping: {
    lead: "NEW",
    approved: "ACCEPTED",
    rejected: "DECLINED",
    ftd: "FTD",
  },
  rateLimitPerMin: 90,
  samplePayload: {
    name: "Maria",
    surname: "Silva",
    email: "maria@t.io",
    mobile: "+5511987654321",
    country_iso: "BR",
    aff_click_id: "click-abc",
  },
  sampleResponse: { data: { id: "iq-557788", status: "lead" } },
};
