import type { Prisma } from "@prisma/client";

export const octafxStyle: Prisma.BrokerTemplateCreateInput = {
  slug: "octafx-style-v1",
  name: "OctaFX-style (generic forex)",
  vendor: "OctaFX-style",
  vertical: "forex",
  protocol: "rest-json",
  status: "active",
  countries: ["ID", "MY", "TH", "IN", "PK"],
  description: "Generic forex broker template modeled after OctaFX's affiliate API shape.",
  defaultHttpMethod: "POST",
  defaultHeaders: { "content-type": "application/json" },
  defaultAuthType: "BEARER",
  authConfigSchema: {
    type: "object",
    required: ["token"],
    properties: { token: { type: "string", minLength: 16 } },
  },
  fieldMapping: {
    firstName: "first_name",
    lastName: "last_name",
    email: "email",
    phone: "phone",
    geo: "country",
    subId: "affiliate_sub_id",
  },
  requiredFields: ["first_name", "last_name", "email", "phone", "country"],
  staticPayload: { source: "gambchamp" },
  responseIdPath: "$.data.lead_id",
  postbackLeadIdPath: "$.lead_id",
  postbackStatusPath: "$.event",
  statusMapping: {
    registration: "NEW",
    kyc_verified: "ACCEPTED",
    kyc_rejected: "DECLINED",
    first_deposit: "FTD",
  },
  rateLimitPerMin: 120,
  samplePayload: {
    first_name: "Sample",
    last_name: "Trader",
    email: "sample@t.io",
    phone: "+628123456789",
    country: "ID",
    affiliate_sub_id: "aff-001",
  },
  sampleResponse: { data: { lead_id: "ocx-abc-001", status: "registration" } },
};
