import type { Prisma } from "@prisma/client";

export const olymptradeStyle: Prisma.BrokerTemplateCreateInput = {
  slug: "olymptrade-style-v1",
  name: "OlympTrade-style (CIS/EU)",
  vendor: "OlympTrade-style",
  vertical: "forex",
  protocol: "rest-json",
  status: "active",
  countries: ["RU", "UA", "PL", "CZ"],
  description: "OlympTrade-style intake — bearer auth; Cyrillic-friendly field names.",
  defaultHttpMethod: "POST",
  defaultHeaders: { "content-type": "application/json; charset=utf-8" },
  defaultAuthType: "BEARER",
  authConfigSchema: {
    type: "object",
    required: ["token"],
    properties: { token: { type: "string", minLength: 24 } },
  },
  fieldMapping: {
    firstName: "f_name",
    lastName: "l_name",
    email: "email",
    phone: "phone",
    geo: "country_code",
    subId: "cid",
  },
  requiredFields: ["f_name", "l_name", "email", "phone", "country_code"],
  staticPayload: { utm_source: "gambchamp" },
  responseIdPath: "$.lead.id",
  postbackLeadIdPath: "$.lead_id",
  postbackStatusPath: "$.new_status",
  statusMapping: {
    created: "NEW",
    verified: "ACCEPTED",
    trashed: "DECLINED",
    first_deposit: "FTD",
  },
  rateLimitPerMin: 60,
  samplePayload: {
    f_name: "Taras",
    l_name: "Koval",
    email: "taras@t.io",
    phone: "+380501234567",
    country_code: "UA",
    cid: "olp-1",
  },
  sampleResponse: { lead: { id: "olp-112233", new_status: "created" } },
};
