import type { Prisma } from "@prisma/client";

export const quotexStyle: Prisma.BrokerTemplateCreateInput = {
  slug: "quotex-style-v1",
  name: "Quotex-style (open sandbox)",
  vendor: "Quotex-style",
  vertical: "forex",
  protocol: "rest-json",
  status: "active",
  countries: ["IN", "BR"],
  description: "Quotex-style intake — open sandbox endpoint, no auth (integration-test only).",
  defaultHttpMethod: "POST",
  defaultHeaders: { "content-type": "application/json" },
  defaultAuthType: "NONE",
  authConfigSchema: { type: "object" },
  fieldMapping: {
    firstName: "firstName",
    lastName: "lastName",
    email: "email",
    phone: "phoneNumber",
    geo: "country",
    subId: "ref",
  },
  requiredFields: ["firstName", "email", "phoneNumber", "country"],
  staticPayload: { tag: "gambchamp" },
  responseIdPath: "$.id",
  postbackLeadIdPath: "$.id",
  postbackStatusPath: "$.status",
  statusMapping: {
    created: "NEW",
    verified: "ACCEPTED",
    rejected: "DECLINED",
    deposited: "FTD",
  },
  rateLimitPerMin: 30,
  samplePayload: {
    firstName: "Rahul",
    lastName: "Kumar",
    email: "rahul@t.io",
    phoneNumber: "+919812345678",
    country: "IN",
    ref: "qx-001",
  },
  sampleResponse: { id: "qx-123456", status: "created" },
};
