import type { Prisma } from "@prisma/client";

export const xmStyle: Prisma.BrokerTemplateCreateInput = {
  slug: "xm-style-v1",
  name: "XM-style (global)",
  vendor: "XM-style",
  vertical: "forex",
  protocol: "rest-json",
  status: "active",
  countries: [
    "AU",
    "BR",
    "CL",
    "DE",
    "ES",
    "FR",
    "GR",
    "HK",
    "ID",
    "IN",
    "IT",
    "JP",
    "MX",
    "MY",
    "PH",
    "PL",
    "SG",
    "TH",
    "UK",
    "ZA",
  ],
  description: "XM-style intake — global coverage; bearer auth with nested response.",
  defaultHttpMethod: "POST",
  defaultHeaders: { "content-type": "application/json", accept: "application/json" },
  defaultAuthType: "BEARER",
  authConfigSchema: {
    type: "object",
    required: ["token"],
    properties: { token: { type: "string", minLength: 24 } },
  },
  fieldMapping: {
    firstName: "firstName",
    lastName: "lastName",
    email: "email",
    phone: "phone",
    geo: "countryOfResidence",
    subId: "affiliateCode",
  },
  requiredFields: ["firstName", "lastName", "email", "phone", "countryOfResidence"],
  staticPayload: { programme: "affiliate-gambchamp" },
  responseIdPath: "$.response.data.clientId",
  postbackLeadIdPath: "$.clientId",
  postbackStatusPath: "$.status",
  statusMapping: {
    prospect: "NEW",
    verified: "ACCEPTED",
    rejected: "DECLINED",
    funded: "FTD",
  },
  rateLimitPerMin: 120,
  samplePayload: {
    firstName: "Yuki",
    lastName: "Tanaka",
    email: "yuki@t.io",
    phone: "+819012345678",
    countryOfResidence: "JP",
    affiliateCode: "xm-aff-001",
  },
  sampleResponse: { response: { data: { clientId: "xm-998877", status: "prospect" } } },
};
