export interface InventoryInput {
  id: string;
  title: string;
  counts: Record<string, number>;
}

const SOURCE_TO_FILE: Record<string, string> = {
  prisma: "db-schema",
  trpc: "trpc-surface",
  rest: "rest-surface",
  env: "env-vars",
  errors: "error-catalog",
  telegram: "telegram-events",
  jobs: "jobs",
  invariants: "invariants",
};

export function renderInventory(blocks: InventoryInput[]): string {
  const lines: string[] = [
    "# CRM Feature Inventory",
    "",
    "> Auto-generated by `pnpm docs:regen`. Do not edit by hand — edit the block catalog or invariants files.",
    "",
  ];
  for (const b of blocks) {
    lines.push(`## ${b.title}`);
    lines.push(`- **Block id:** \`${b.id}\``);
    lines.push(`- **Human-layer directory:** \`content/docs/${b.id}/\``);
    lines.push(`- **AI-deep directory:** \`content/docs/${b.id}/_deep/\``);
    lines.push("");
    lines.push("| Source | Count | Link |");
    lines.push("|---|---:|---|");
    for (const [src, n] of Object.entries(b.counts)) {
      if (!n) continue;
      const fileName = SOURCE_TO_FILE[src] ?? src;
      lines.push(
        `| ${src} | ${n} | [${fileName}.md](../content/docs/${b.id}/_deep/${fileName}.md) |`,
      );
    }
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}
