export const TELEGRAM_EVENT_TYPES = [
  "NEW_LEAD",
  "PUSHED",
  "ACCEPTED",
  "DECLINED",
  "FTD",
  "FAILED",
  "FRAUD_HIT",
  "MANUAL_REVIEW_QUEUED",
  "PENDING_HOLD_START",
  "PENDING_HOLD_RELEASED",
  "SHAVE_SUSPECTED",
  "BROKER_DOWN",
  "BROKER_RECOVERED",
  "CAP_REACHED",
  "AUTOLOGIN_DOWN",
  "AUTOLOGIN_SLA_BREACHED",
  "PROXY_POOL_DEGRADED",
  "DAILY_SUMMARY",
  "ANOMALY_DETECTED",
  "FRAUD_POLICY_CHANGED",
  "BROKER_CONFIG_CHANGED",
  "AFFILIATE_DAILY_SUMMARY",
  "AFFILIATE_FTD",
  "ALERT_TRIGGERED",
  "SCHEDULED_CHANGE_APPLIED",
  "SCHEDULED_CHANGE_FAILED",
  "STATUS_MAPPING_BACKFILL_PROGRESS",
  // v2.0 S2.0-3 Stripe billing
  "SUBSCRIPTION_CREATED",
  "SUBSCRIPTION_RENEWED",
  "SUBSCRIPTION_CANCELED",
  "INVOICE_PAID",
  "INVOICE_FAILED",
] as const;

export type TelegramEventType = (typeof TELEGRAM_EVENT_TYPES)[number];

export const ADMIN_ONLY_EVENTS: ReadonlySet<TelegramEventType> = new Set<TelegramEventType>([
  "BROKER_CONFIG_CHANGED",
  "FRAUD_POLICY_CHANGED",
  "AUTOLOGIN_DOWN",
  "AUTOLOGIN_SLA_BREACHED",
  "PROXY_POOL_DEGRADED",
  "SCHEDULED_CHANGE_APPLIED",
  "SCHEDULED_CHANGE_FAILED",
  "STATUS_MAPPING_BACKFILL_PROGRESS",
  "SUBSCRIPTION_CREATED",
  "SUBSCRIPTION_RENEWED",
  "SUBSCRIPTION_CANCELED",
  "INVOICE_PAID",
  "INVOICE_FAILED",
]);

export function isTelegramEventType(v: string): v is TelegramEventType {
  return (TELEGRAM_EVENT_TYPES as readonly string[]).includes(v);
}
